CREATE TABLE Students (
    SID NUMBER PRIMARY KEY,
    SNAME VARCHAR2(50) NOT NULL,
    SMAJOR VARCHAR2(50)
);

INSERT INTO Students (SID, SNAME, SMAJOR) VALUES
    (110, 'Liam', 'History'),
    (111, 'Mia', 'Art'),
    (112, 'Noah', 'Biology');

CREATE TABLE GRADUATES (
    GID NUMBER PRIMARY KEY,
    GNAME VARCHAR2(50) NOT NULL,
    GYEAR NUMBER
);

INSERT INTO GRADUATES (GID, GNAME, GYEAR) VALUES
    (101, 'Alice', 2023),
    (103, 'Carol', 2024),
    (106, 'Frank', 2025);

SELECT SNAME FROM Students
UNION
SELECT GNAME FROM GRADUATES;

SELECT SNAME FROM Students
INTERSECT
SELECT GNAME FROM GRADUATES;
